#!/usr/bin/env bash

[[ "${1,,}" != *(\-)@(h)?(elp) ]] || { cat <<'EOL'
COMMAND:   min
SYNOPSIS:
   Outputs the least value from all numerical inputs,
    which may be supplied from either or both directions.

EOL
	exit 0
}

{ printf '%s\n' $({ [ -t 0 ] || cat - ; echo ${@} ; }) | sort -rn | tail -n1 ; } 2>/dev/null
